@baseUrl = http://localhost:5248

### Register a new user
POST {{baseUrl}}/api/Auth/register
Content-Type: application/json

{
  "username": "Test1",
  "email": "test3@example.com",
  "password": "Password1!"
}

### Login
POST {{baseUrl}}/api/Auth/login
Content-Type: application/json

{
  "username": ,
  "password": "Password1!"
}

### Access secure endpoint WITHOUT a token (expect 401)
GET {{baseUrl}}/api/Test/secure

### Access secure endpoint WITH a token (expect 200)
GET {{baseUrl}}/api/Test/secure
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTU1OTg4MC1iMjU5LTQyOTktYTNkYS01OGQzYjBmZDQ0MzYiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4NDUwMzc5MSwiaXNzIjoiUm9va0FwaSIsImF1ZCI6IlJvb2tDbGllbnQifQ.rfY_qKJ70b1x0_Wsf-X6JyV865nh5TSpwXGoV8eEfNE

### Admin-only endpoint with a non-admin token (expect 403)
GET {{baseUrl}}/api/Test/admin-only
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTU1OTg4MC1iMjU5LTQyOTktYTNkYS01OGQzYjBmZDQ0MzYiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MzYzMjYxNCwiaXNzIjoiUm9va0FwaSIsImF1ZCI6IlJvb2tDbGllbnQifQ.LP_i7xxmPuiGO6yT5nm9wRxYbyT4noUiyEKNsLp27c0

### Logout
POST {{baseUrl}}/api/Auth/refresh
Content-Type: application/json

{
  "refreshToken": "BrcTHviUeYq/iw2OoD1yR/J4XEKAvDQau8P/4FIqqZ0OT/0vXz8MXdH6tmdPJFFm72poW3KkHvwhBTAtehCjLQ=="
}